const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const LOADING = 'LOADING';
const SET_USER = 'SET_USER';
const SET_ERROR = 'SET_ERROR';
const ON_CHANGE_SLEEP_FORM = 'ON_CHANGE_SLEEP_FORM';

export default {
	LOGIN,
	SIGNUP,
	LOADING,
	SET_USER,
	SET_ERROR,
	ON_CHANGE_SLEEP_FORM,
}